# Generated by Django 4.0.4 on 2022-05-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('end_trails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='endingpoint',
            old_name='endLat',
            new_name='end_lat',
        ),
        migrations.RenameField(
            model_name='endingpoint',
            old_name='endLng',
            new_name='end_lng',
        ),
    ]
