# Generated by Django 4.0.4 on 2022-05-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0001_initial'),
        ('end_trails', '0002_rename_endlat_endingpoint_end_lat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EndingPoint',
            new_name='EndTrail',
        ),
    ]
