# Generated by Django 4.0.4 on 2022-05-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StartingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startLat', models.FloatField()),
                ('startLng', models.FloatField()),
            ],
        ),
    ]
