# Generated by Django 4.0.4 on 2022-05-22 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('end_trails', '0001_initial'),
        ('start_trails', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trail_name', models.CharField(max_length=70)),
                ('difficulty', models.IntegerField()),
                ('trail_end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='end_trails.endingpoint')),
                ('trail_start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='start_trails.startingpoint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
