# Generated by Django 4.0.4 on 2022-05-23 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('start_trails', '0002_rename_startingpoint_starttrail_and_more'),
        ('trails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='start_trails.starttrail'),
        ),
        migrations.AlterField(
            model_name='trail',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
