# Generated by Django 4.0.4 on 2022-05-23 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('end_trails', '0003_rename_endingpoint_endtrail'),
        ('trails', '0002_alter_trail_trail_start_alter_trail_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='trail_end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='end_trails.endtrail'),
        ),
    ]
